name: Docker Image CI

on:
  push:
    branches:
      - "main"
      
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops_task14_web_ui:latest
          
          
  deploy:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_GITHUB_ACTION }} 
          known_hosts: 'host'
      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
        
      - name: Git clone
        uses: actions/checkout@v3
        with:
          repository: stranger7771981/devops_task14_web_ui
          ssh-known-hosts: ${{ secrets.SSH_HOST }}
    
      - name: Run SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_GITHUB_ACTION}}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pwd
            
    
      - name: Ansible
        run:  ansible-playbook -i hosts.yml playbook_ansible.yml 
    
